name: Build

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            ccache \
            ecj \
            fastjar \
            gettext \
            java-propose-classpath \
            libelf-dev \
            libncurses5-dev \
            libncursesw5-dev \
            xsltproc
      - run: make
