name: Build

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: make
        run: |
          make
          echo "::set-output name=name::openwrt-img"
          echo "::set-output name=path::$(find . -wholename '*/bin/*-sysupgrade.bin' -exec dirname \{\} \;)"
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.make.outputs.name }}
          path: ${{ steps.make.outputs.path }}
