name: Build

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt list --installed
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install \
            ccache \
            ecj \
            fastjar \
            gawk \
            gettext \
            java-propose-classpath \
            libelf-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libssl-dev \
            python3-distutils \
            python3-setuptools \
            xsltproc \
            zlib1g-dev 
