name: Build

on:
  workflow_dispatch:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends \
            ccache \
            ecj \
            fastjar \
            gettext \
            java-propose-classpath \
            libelf-dev \
            libncurses5-dev \
            libncursesw5-dev \
            xsltproc
      - id: make
        run: |
          make
          echo '::set-output name=name::openwrt-image'
          echo '::set-output name=path::openwrt/bin/targets/ath79/generic/'
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.make.outputs.name }}
          path: ${{ steps.make.outputs.path }}
